import {esc} from '../../lib/utils.js';
import {panel} from '../components/panel.js';
import {store} from '../../app/state.js';
import {buildIntelligence} from '../../intelligence.js';
export function intelligenceView(ctx){const {s,active,briefing,modelOps={versions:[],drift:[]},aiStatus={}}=ctx,intel=buildIntelligence(active,store.feedback),ready=store.state.step===s.events.length&&(!store.state.apiOnline||(store.processedSteps[s.id]||0)===s.events.length),visibleFeedback=store.feedback.filter(f=>f.scenarioId===s.id&&(ready||(f.runId||0)<(store.runIds[s.id]||0)));return `<div class="layout-grid layout-grid--2"><div class="stack">
  ${panel('Recurring attack patterns',`<div class="list-table">${intel.patterns.map(p=>`<div class="list-table__row"><strong>${esc(p.label)}</strong><span>${p.count} observed events · ${esc(p.evidence.join(', '))}<br>First ${esc(p.firstSeen)} · Last ${esc(p.lastSeen)}<br>Assets: ${esc(p.assets.join(', ')||'unattributed')} · Incidents: ${esc(p.incidentIndices.map(i=>ctx.scenarios[i]?.incidentId).join(', '))}</span></div>`).join('')||'<div class="empty-state"><p>No recurring event type in the available history.</p></div>'}</div><p class="text-muted">Source: ${intel.observedEvents} observed events across the incident portfolio.</p>`)}
  ${panel('Recurring suspicious entities',`<div class="list-table">${intel.recurringEntities.map(x=>`<div class="list-table__row"><strong>${esc(x.kind)}: ${esc(x.value)}</strong><span>${x.events.length} events · ${esc(x.events.join(', '))}</span></div>`).join('')||'<div class="empty-state"><p>No recurring entity observed.</p></div>'}</div><p class="text-muted">Recurrence alone does not imply malicious intent.</p>`)}
  ${panel('Emerging behavioral trends',`<div class="trend-stack">${intel.trends.map(t=>`<div><strong>${esc(t.type)}: ${esc(t.direction)}</strong><p>${t.first} in the earlier half of observed events; ${t.second} in the later half.</p></div>`).join('')}</div><p class="text-muted">Time window: ${intel.observedEvents} observed events, split chronologically. Feedback-informed threshold changes do not retrain the model.</p>`)}
  ${panel('Continuous learning status',`<div class="briefing-card"><p><strong>Effective threshold:</strong> ${ctx.a.threshold} anomaly/context signals</p><p><strong>Feedback applied:</strong> ${ctx.a.feedbackImpact.confirmedAttacks} confirmed attack(s), ${ctx.a.feedbackImpact.falsePositives} false positive(s), ${ctx.a.feedbackImpact.needsInvestigation} pending investigation classification(s).</p><p><strong>Current disposition:</strong> ${esc(ctx.a.disposition)}</p><p class="text-muted">Analyst outcomes adjust the scenario threshold for later replay runs. The seeded anomaly model itself remains deterministic.</p></div>`)}
  ${panel('Model operations',`<div class="briefing-card"><p><strong>Active version:</strong> ${esc(modelOps.activeVersion||'unavailable')}</p><p><strong>Registered versions:</strong> ${modelOps.versions.length}</p><p><strong>Latest drift:</strong> ${modelOps.drift[0]?`${esc(modelOps.drift[0].status)} · ${(modelOps.drift[0].score*100).toFixed(1)}% across ${modelOps.drift[0].sampleCount} samples`:'No drift measurement recorded'}</p><p class="text-muted">Candidate versions require offline evaluation and explicit administrator promotion. Active versions retain a rollback parent.</p></div>`)}
  ${panel('Analyst feedback',`<div class="btn-row"><button type="button" class="btn btn--secondary" data-feedback="confirmed_attack" ${ready?'':'disabled'}>Confirmed attack</button><button type="button" class="btn btn--secondary" data-feedback="false_positive" ${ready?'':'disabled'}>False positive</button><button type="button" class="btn btn--secondary" data-feedback="needs_investigation" ${ready?'':'disabled'}>Need more investigation</button></div>${ready?'':'<p class="text-muted">Complete the replay before classifying the incident.</p>'}<textarea id="feedback-reason" class="input input--textarea" placeholder="Required reason for classification…" ${ready?'':'disabled'}></textarea><div class="feedback-list">${visibleFeedback.map(f=>`<div class="feedback-item"><strong>${esc(f.classification.replaceAll('_',' '))}</strong><small>${esc(f.reason)} · ${esc(f.analyst)} · ${esc(f.timestamp)}</small></div>`).join('')||'<div class="empty-state"><p>No feedback recorded for this incident.</p></div>'}</div>`)}
  </div><div class="stack">
  ${panel('Proactive risk watchlist',`<div class="watchlist">${intel.watchlist.map(x=>`<div class="watchlist__item"><span class="watchlist__icon">◇</span><div><strong>${esc(x.value)}</strong><small>${esc(x.kind)} · incident risk ${x.risk}/100 · evidence ${esc(x.evidence.join(', '))}</small></div></div>`).join('')||'<div class="empty-state"><p>No entity meets the current high-risk watchlist threshold.</p></div>'}</div><p class="text-muted">Watchlist means review priority, not a malicious-activity finding.</p>`)}
  ${panel('Automated security suggestions',`<div>${intel.suggestions.map(x=>`<div class="intel-card"><span class="intel-card__tag">Automated evidence-based suggestion</span><strong>${esc(x.label)}</strong><small>Supporting events: ${esc(x.evidence.join(', '))}</small></div>`).join('')||'<div class="empty-state"><p>Recommendations appear when evidence supports them.</p></div>'}</div>`)}
  ${panel('Administrator briefing',`<div class="briefing-card"><div class="briefing-card__stats"><div><strong>${briefing.activeIncidents}</strong><span>Active</span></div><div><strong>${briefing.criticalIncidents}</strong><span>Critical</span></div><div><strong>${briefing.pendingApprovals}</strong><span>Pending</span></div></div><p><strong>Affected assets:</strong> ${esc(briefing.affectedAssets.join(', ')||'none')}</p><p><strong>Emerging patterns:</strong> ${esc(briefing.emergingPatterns.join('; ')||'none observed')}</p><ul class="briefing-list">${briefing.priorities.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><p class="text-muted">${esc(briefing.label)}</p></div>`)}
  ${panel('Investigation AI controls',`<div class="briefing-card"><p><strong>Provider:</strong> ${esc(aiStatus.provider||'deterministic-fallback')}</p><p><strong>Grounding:</strong> ${esc(aiStatus.grounding||'local evidence templates')}</p><p><strong>Controls:</strong> citation validation, prompt-injection rejection, secret redaction, timeout, and deterministic fallback.</p></div>`)}
  </div></div>`;}
