import {esc} from '../../lib/utils.js';
import {panel} from '../components/panel.js';
import {store} from '../../app/state.js';

export function operationsView(){
  const connector=store.connectors?.wazuh||{},models=store.modelOps||{versions:[]},busy=store.state.operationBusy;
  const disabled=busy||!store.state.apiOnline?'disabled':'';
  return `<div class="layout-grid layout-grid--2"><div class="stack">
    ${panel('Wazuh read-only connection',`<p><strong>Status:</strong> ${esc(connector.status||(connector.configured?'Configured; not yet queried':'Configuration required'))}</p><p>Credentials stay in server environment variables. This connector reads Wazuh alerts and never executes containment commands.</p><p><strong>Last successful collection:</strong> ${esc(connector.lastSuccess||'None')}</p><p><strong>Last batch:</strong> ${connector.imported||0} imported · ${connector.duplicates||0} duplicates</p>${connector.lastError?`<p role="alert">${esc(connector.lastError)}</p>`:''}<div class="btn-row"><button class="btn btn--primary" data-action="poll-wazuh" ${disabled} ${connector.configured?'':'disabled'}>Collect Wazuh alerts</button><button class="btn btn--secondary" data-action="refresh-operations" ${disabled}>Refresh status</button></div><p class="text-muted">Set SENTINEL_X_WAZUH_URL, SENTINEL_X_WAZUH_USER and SENTINEL_X_WAZUH_PASSWORD locally. Use a read-only indexer account. Automatic collection is opt-in.</p>`)}
    ${panel('Authenticated telemetry',`<p>Push validated real events to <code>POST /api/v1/telemetry/events</code> with a server-configured bearer token. Duplicate event IDs are ignored. Source-provided severity is retained for reference and is not trusted as a risk score.</p><p class="text-muted">Real telemetry and simulated containment are labeled separately. This single-process workspace currently caps each real source at 300 events.</p>`)}
    ${panel('Autonomous external investigation',`<p>Open a real-telemetry incident in Investigation and select <strong>Investigate external evidence</strong>. The planner follows observed device, account and IP relationships through read-only Wazuh queries, stops at its query/time budget, and preserves the query trace.</p><p class="text-muted">Enable SENTINEL_X_EXTERNAL_INVESTIGATIONS=1 for automatic investigation after detection. Queries never extend beyond the selected evidence timestamp.</p>`)}
  </div><div class="stack">
    ${panel('Train and evaluate a model',`<p>Upload JSON containing reviewed normal <code>trainingEvents</code> and separate labeled <code>evaluationEvents</code>, a <code>version</code>, and <code>datasetName</code>. Training runs in a worker and saves a reproducible forest artifact.</p><label class="field"><span>Training dataset JSON</span><input class="input" id="training-file" type="file" accept=".json,application/json" ${disabled}></label><label class="field"><span><input id="training-approved" type="checkbox" ${disabled}> I reviewed the normal training labels and the held-out evaluation labels.</span></label><div class="btn-row"><button class="btn btn--primary" data-action="train-model" ${disabled}>Train uploaded dataset</button><button class="btn btn--secondary" data-action="download-training-example" ${disabled}>Download synthetic example</button></div><p class="text-muted">The example is synthetic lab data, not a production benchmark. Training does not automatically deploy a candidate.</p>`)}
    ${panel('Deployed detection model',`<p><strong>Active inference version:</strong> ${esc(models.activeVersion||'Unavailable')}</p><label class="field"><span>Candidate version</span><select id="model-version" class="input" ${disabled}>${models.versions.filter(v=>v.status!=='active'&&v.metrics.eligible===true).map(v=>`<option value="${esc(v.version)}">${esc(v.version)}</option>`).join('')}</select></label><div class="btn-row"><button class="btn btn--primary" data-action="promote-model" ${disabled}>Deploy evaluated model</button><button class="btn btn--secondary" data-action="rollback-model" ${disabled}>Roll back model</button></div><div class="list-table">${models.versions.map(v=>`<div class="list-table__row"><strong>${esc(v.version)} · ${esc(v.status)}</strong><span>${v.metrics.evaluationCount?`${v.metrics.trainingCount} training / ${v.metrics.evaluationCount} evaluation events · precision ${Math.round(v.metrics.precision*100)}% · recall ${Math.round(v.metrics.recall*100)}% · ${v.metrics.eligible?'passes gate':'fails gate'}`:'Bundled demo baseline or metadata-only record'}</span></div>`).join('')}</div><p class="text-muted">Promotion changes the model used by server and browser analysis. Rollback restores its prior version. Evaluation numbers describe the supplied dataset only.</p>`)}
  </div></div>${busy?'<p role="status">Operation in progress…</p>':''}`;
}
