/** Seeded Isolation Forest with an explicit out-of-baseline novelty term. */
function random(seed) { let state=seed>>>0; return () => {state=(1664525*state+1013904223)>>>0;return state/4294967296;}; }
function cFactor(n){if(n<=1)return 0;return 2*(Math.log(n-1)+0.5772156649)-2*(n-1)/n;}
function build(points,depth,maxDepth,rng){if(depth>=maxDepth||points.length<=1)return {size:points.length};const varying=[];for(let d=0;d<points[0].length;d++){const values=points.map(p=>p[d]);if(Math.min(...values)<Math.max(...values))varying.push(d);}if(!varying.length)return {size:points.length};const dim=varying[Math.floor(rng()*varying.length)];const vals=points.map(p=>p[dim]);const lo=Math.min(...vals),hi=Math.max(...vals),split=lo+rng()*(hi-lo);const left=points.filter(p=>p[dim]<split),right=points.filter(p=>p[dim]>=split);if(!left.length||!right.length)return {size:points.length};return {dim,split,left:build(left,depth+1,maxDepth,rng),right:build(right,depth+1,maxDepth,rng)};}
function path(point,tree,depth=0){if('size'in tree)return depth+cFactor(tree.size);return path(point,point[tree.dim]<tree.split?tree.left:tree.right,depth+1);}
export class IsolationForest{
  constructor(trees=64,sampleSize=64,maxDepth=8,seed=271828){this.trees=trees;this.sampleSize=sampleSize;this.maxDepth=maxDepth;this.seed=seed;this.forest=[];this.min=[];this.max=[];}
  fit(data){if(!Array.isArray(data)||!data.length)throw Error('Training data required');const dims=data[0].length;if(data.some(p=>p.length!==dims||p.some(v=>!Number.isFinite(v))))throw Error('Invalid training features');this.min=Array.from({length:dims},(_,d)=>Math.min(...data.map(p=>p[d])));this.max=Array.from({length:dims},(_,d)=>Math.max(...data.map(p=>p[d])));const rng=random(this.seed);const n=Math.min(this.sampleSize,data.length);this.forest=Array.from({length:this.trees},()=>build(Array.from({length:n},()=>data[Math.floor(rng()*data.length)]),0,this.maxDepth,rng));this.effectiveSample=n;return this;}
  score(point){if(!this.forest.length)return 0.5;const avg=this.forest.reduce((s,t)=>s+path(point,t),0)/this.forest.length;const isolation=Math.pow(2,-avg/Math.max(cFactor(this.effectiveSample),1));const novelty=point.reduce((n,v,d)=>{const width=Math.max(this.max[d]-this.min[d],0.05);return n+Math.min(1,Math.max(0,this.min[d]-v,v-this.max[d])/width);},0)/point.length;return Math.min(1,isolation+0.35*novelty);}
  scoreBatch(points){return points.map(p=>this.score(p));}
  toJSON(){return {trees:this.trees,sampleSize:this.sampleSize,maxDepth:this.maxDepth,seed:this.seed,forest:this.forest,min:this.min,max:this.max,effectiveSample:this.effectiveSample};}
  static fromJSON(data){
    if(!data||!Array.isArray(data.forest)||data.forest.length<1||data.forest.length>128||!Array.isArray(data.min)||data.min.length!==6||!Array.isArray(data.max)||data.max.length!==6||data.min.some((v,i)=>!Number.isFinite(v)||!Number.isFinite(data.max[i])||v>data.max[i])||!Number.isInteger(data.effectiveSample)||data.effectiveSample<1||data.effectiveSample>2048)throw Error('Invalid forest artifact');
    let nodes=0;const validate=(node,depth=0)=>{if(!node||++nodes>100000||depth>16)throw Error('Invalid forest tree');if('size'in node){if(!Number.isInteger(node.size)||node.size<0)throw Error('Invalid leaf');return;}if(!Number.isInteger(node.dim)||node.dim<0||node.dim>=6||!Number.isFinite(node.split))throw Error('Invalid split');validate(node.left,depth+1);validate(node.right,depth+1);};
    data.forest.forEach(tree=>validate(tree));
    const model=new IsolationForest();Object.assign(model,data);return model;
  }
}
export function eventFeatures(event,baseline,knownDevices=baseline.knownDevices||[],knownIPs=baseline.knownIPs||[]){const hour=new Date(event.timestamp).getUTCHours();return [(event.normalized?.failures||0)/30,(event.normalized?.bytes||0)/3e9,hour/24,event.device&&!knownDevices.includes(event.device)?1:0,event.ip&&!knownIPs.includes(event.ip)?1:0,['privilege_escalation','sensitive_access','internal_access','outbound_transfer'].includes(event.type)?1:0];}
export function trainForestFromBaseline(baseline,normalEvents=[]){const knownDevices=baseline.knownDevices||[],knownIPs=baseline.knownIPs||[];const training=normalEvents.length?normalEvents.map(e=>eventFeatures(e,baseline,knownDevices,knownIPs)):Array.from({length:120},(_,i)=>{const k=(i*37)%120;return [((k%6)/100),((k%11)/200),(baseline.loginHourMedian+(k%5)-2)/24,0,0,0];});const forest=new IsolationForest().fit(training);return {forest,knownDevices,knownIPs};}
