/** HTML report for PDF export (print-to-PDF in browser or server render). */

export function reportHtml(data) {
  const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>SENTINEL-X Report ${esc(data.incidentId)}</title>
<style>
body{font-family:Arial,sans-serif;margin:40px;color:#111;line-height:1.5}
h1{font-size:22px;border-bottom:2px solid #2a7a5f;padding-bottom:8px}
h2{font-size:14px;color:#2a7a5f;margin-top:24px;text-transform:uppercase;letter-spacing:.05em}
.meta{font-size:12px;color:#555}
table{width:100%;border-collapse:collapse;font-size:12px;margin-top:8px}
td,th{border:1px solid #ccc;padding:6px 8px;text-align:left}
th{background:#f4f4f4}
.tag{display:inline-block;background:#e8f5ef;border:1px solid #2a7a5f;padding:2px 6px;font-size:10px;margin-right:4px}
.warn{background:#fff3e0;border-color:#e65100}
</style></head><body>
<h1>SENTINEL-X Incident Report</h1>
<p class="meta">Incident: <b>${esc(data.incidentId)}</b> · Severity: <b>${esc(data.severity)}</b> · Confidence: <b>${Math.round((data.confidence || 0) * 100)}%</b> · Mode: <span class="tag">${data.simulation ? 'SIMULATION' : 'REAL TELEMETRY / SIMULATED RESPONSE'}</span></p>
<h2>Threat Summary</h2><p>${esc(data.threatSummary)}</p>
<h2>Attack Sequence</h2><ol>${(data.attackSequence || []).map(s => `<li>${esc(s.name)} <span class="tag">${esc(s.label)}</span> — ${esc(s.eventId)}</li>`).join('')}</ol>
<h2>Timeline</h2><table><tr><th>Time</th><th>ID</th><th>Action</th></tr>${(data.timeline || []).map(e => `<tr><td>${esc(e.time)}</td><td>${esc(e.id)}</td><td>${esc(e.action)}</td></tr>`).join('')}</table>
<h2>Blast Radius</h2><table><tr><th>Entity</th><th>Count</th></tr>${Object.entries(data.blastRadius || {}).map(([k, v]) => `<tr><td>${esc(k)}</td><td>${v}</td></tr>`).join('')}</table>
<h2>Risk Assessment</h2><p>Score: <b>${data.risk?.score || 0}/100</b></p><ul>${(data.risk?.factors || []).map(f => `<li>+${f.points} ${esc(f.label)}</li>`).join('')}</ul>
<h2>AI Reasoning</h2><p><b>Observed:</b></p><ul>${(data.reasoning?.observed || []).map(o => `<li>${esc(o)}</li>`).join('')}</ul>
<p><b>Inference:</b> ${esc(data.reasoning?.inference)}</p>
<p><b>Uncertainty:</b> ${esc(data.reasoning?.uncertainty)}</p>
<h2>Remaining Uncertainty</h2><ul>${(data.remainingUncertainty || []).map(u => `<li class="warn tag">${esc(u)}</li>`).join('')}</ul>
<h2>Response Actions</h2><table><tr><th>Action</th><th>Status</th><th>Actor</th><th>Time</th></tr>${(data.responseActions || []).map(a => `<tr><td>${esc(a.action)}</td><td>${esc(a.status)}</td><td>${esc(a.actor)}</td><td>${esc(a.timestamp)}</td></tr>`).join('') || '<tr><td colspan="4">None</td></tr>'}</table>
<h2>Human Approvals</h2><ul>${(data.humanApprovals || []).map(a => `<li>${esc(a.detail)} — ${esc(a.actor)} (${esc(a.timestamp)})</li>`).join('') || '<li>None</li>'}</ul>
<h2>Resolution</h2><p>Status: <b>${esc(data.resolutionStatus)}</b></p>
<p>Recommended follow-up: ${esc(data.recommendedFollowUp)}</p>
<p class="meta">Generated by SENTINEL-X · ${new Date().toISOString()}</p>
</body></html>`;
}
