import {versionedPath,pageParameters} from './versionedApi.js';
import {observePipeline} from './operations.js';
import {loginLocal,refreshLocal,logoutLocal} from './sessions.js';
import {AsyncLocalStorage} from 'node:async_hooks';
import {randomUUID} from 'node:crypto';
import {scenarios} from '../src/scenarios.js';
import {analyze,normalize,report,reportCsv,reportPdfHtml,setPolicy,setWeights,securityBriefing,compareIncidents,DEFAULT_WEIGHTS,DEFAULT_POLICY,setModelArtifact} from '../src/engine.js';
import {renderReportPdf} from '../services/reportPdf.js';
import {investigateWithGrounding,llmConfigured,llmProvider} from '../services/llmInvestigation.js';
import {runInvestigation} from '../services/investigationAgent.js';
import {investigateExternalEvidence} from '../services/externalInvestigation.js';
import {saveExternalInvestigation,listExternalInvestigations} from './db.js';
import {seedTenant,getPolicy,updatePolicy,getWeights,updateWeights,insertAudit,listAudit,insertFeedback,listFeedback,insertAction,listActions,upsertIncidentStatus,getIncidentStatus,ingestEvent,listIngestedEvents,clearScenarioEvents,listEntities,listTopology,modelOperations,registerModelVersion,promoteModelVersion,rollbackModelVersion,recordModelDrift,enqueueIngestion,updateIngestionJob,ingestionHealth,getIngestionJob,rollbackSimulatedControl,saveSnapshot,listSnapshots,applySimulatedControl,listSimulatedControls,currentRun} from './db.js';
import {deployedArtifact,trainInWorker,saveCandidate,promoteTrainedModel,rollbackTrainedModel} from './models.js';
import {normalizeTelemetry,telemetryAuthorized} from '../services/telemetry.js';
import {queryWazuh,wazuhConfig} from '../services/wazuh.js';
import {getDb,connectorState,saveConnectorState,eventExists} from './db.js';
import {authMode,principalFor,hasRole} from './auth.js';
const tenantScope=new AsyncLocalStorage();
const tenants=new Set(['default',...(process.env.SENTINEL_X_TENANTS||'').split(',').map(x=>x.trim()).filter(x=>/^[a-zA-Z0-9_-]{1,60}$/.test(x))]);
for(const tenant of tenants)seedTenant(tenant);
const tenantId=()=>tenantScope.getStore()||'default';
const sseClients=new Map();const DEMO_TOKEN=randomUUID();
const error=(status,message)=>Object.assign(new Error(message),{status});
const json=(res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(body));};
function parseBody(req){return new Promise((resolve,reject)=>{let data='';req.on('data',chunk=>{data+=chunk;if(data.length>1000000){reject(error(413,'Request body too large'));req.destroy();}});req.on('end',()=>{try{resolve(data?JSON.parse(data):{});}catch{reject(error(400,'Invalid JSON'));}});req.on('error',reject);});}
const realSources=['telemetry','wazuh'];
function scenarioFor(id){if(realSources.includes(id))return {id,name:id==='wazuh'?'Wazuh telemetry':'Authenticated telemetry',incidentId:'SX-'+id.toUpperCase(),entities:{},events:listIngestedEvents(tenantId(),id)};if(id==='live')return {id:'live',name:'Ingested demo events',incidentId:'SX-LIVE',summary:'Evidence from ingested simulated events',entities:{},events:listIngestedEvents(tenantId(),'live')};const found=scenarios.find(s=>s.id===id);if(!found)throw error(404,'Unknown scenario');return found;}
function settings(){setModelArtifact(deployedArtifact(tenantId()));const policy=getPolicy(tenantId())||DEFAULT_POLICY,weights=getWeights(tenantId())||DEFAULT_WEIGHTS;setPolicy(policy);setWeights(weights);return {policy,weights};}
function analysisFor(id,step){const scenario=scenarioFor(id),{policy,weights}=settings(),observed=listIngestedEvents(tenantId(),id).length;if(step!==undefined&&(!Number.isInteger(step)||step<0||step>scenario.events.length))throw error(400,'Invalid historical step');if(step!==undefined&&step>observed)throw error(409,'Historical step has not been ingested');const visible=step??observed,run=currentRun(tenantId(),id),feedback=listFeedback(tenantId(),id).filter(f=>f.runId<run||visible===scenario.events.length);return analyze(scenario,visible,feedback,{policy,weights});}
let pendingBroadcasts=null;
function broadcast(event,data){if(pendingBroadcasts){pendingBroadcasts.push([event,data]);return;}for(const [res,client] of sseClients){if(!principalFor(client.req)){res.end();sseClients.delete(res);continue;}if(client.tenant===tenantId())res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);}}
function audit(type,detail,scenarioId,actor='Demo analyst',step=null){const entry={id:`AUD-${randomUUID()}`,tenantId:tenantId(),scenarioId,type,detail,actor,timestamp:new Date().toISOString(),simulation:!realSources.includes(scenarioId),step};insertAudit(entry);return entry;}
function recordAction(scenarioId,action,status,reason,actor,step,analysis){const target=action.includes('endpoint')?analysis.affected.devices[0]:action.includes('source')?(analysis.events.at(-1)?.ip||analysis.events.at(-1)?.destination||analysis.events.at(-1)?.source):action.includes('session')||action.includes('account')?analysis.affected.accounts[0]:'Security operations queue';const control=status==='rejected'?null:applySimulatedControl(tenantId(),scenarioId,action,target||'Unattributed target');if(action==='create incident'&&control&&!getIncidentStatus(tenantId(),scenarioId)){const s=scenarioFor(scenarioId);upsertIncidentStatus(tenantId(),scenarioId,s.incidentId,'NEW','Created by simulated policy engine');}const entry={id:`ACT-${randomUUID()}`,tenantId:tenantId(),scenarioId,action,status,reason,policyId:analysis.policy.policyId,actor,result:control?`${control.state}; no external system changed`:'No action taken',timestamp:new Date().toISOString(),step,risk:analysis.risk,confidence:analysis.confidence,evidenceIds:analysis.evidence.map(e=>e.id),target};insertAction(entry);audit('approval',`${status}: ${action} on ${target}; risk ${analysis.risk}/100, confidence ${Math.round(analysis.confidence*100)}%, evidence ${entry.evidenceIds.join(', ')}, policy ${entry.policyId}. ${reason}`,scenarioId,actor,step);broadcast('action',entry);return entry;}
function safeAutoResponse(id,a,step){if(!a.detected)return null;const actions=listActions(tenantId(),id),policy=getPolicy(tenantId());let result=null;if(policy.allowedActions.includes('create incident')&&!policy.approvalRequired.includes('create incident')&&!actions.some(x=>x.action==='create incident'&&x.status==='auto-executed'))result=recordAction(id,'create incident','auto-executed','Detection passed contextual threshold; safe incident record created','Demo policy engine',step,a);if(a.policy.action&&!a.policy.approval&&!actions.some(x=>x.action===a.policy.action&&x.status==='auto-executed'))result=recordAction(id,a.policy.action,'auto-executed',a.policy.reason,'Demo policy engine',step,a);return result;}
function processEvent(id,event,step){
  const db=getDb();db.exec('BEGIN IMMEDIATE');pendingBroadcasts=[];let a,auto,queued;
  try{ingestEvent(tenantId(),event);a=analysisFor(id,step);saveSnapshot(tenantId(),id,{step,modelVersion:a.modelVersion,risk:a.risk,confidence:a.confidence,detected:a.detected,evidence:a.evidence.map(e=>e.id),policy:a.policy});audit('ingestion','Ingested '+event.id+'; risk '+a.risk+'/100; '+a.policy.decision,id,realSources.includes(id)?'Authenticated telemetry source':'Demo event source',step);auto=safeAutoResponse(id,a,step);db.exec('COMMIT');queued=pendingBroadcasts;}
  catch(e){db.exec('ROLLBACK');observePipeline('detectionFailures');throw e;}finally{pendingBroadcasts=null;}
  for(const [kind,data] of queued)broadcast(kind,data);observePipeline('ingested');
  broadcast('event',{scenarioId:id,step,event,analysis:{risk:a.risk,detected:a.detected,severity:a.severity},autoAction:auto});
  if(a.detected&&realSources.includes(id)&&process.env.SENTINEL_X_EXTERNAL_INVESTIGATIONS==='1'&&!externalRuns.has(id))void externalRun(id,step,3,'Investigation worker').catch(()=>{});
  return a;
}
function validatePolicy(body){if(!body||typeof body!=='object'||Array.isArray(body))throw error(400,'Policy patch required');if(body.mode&&body.mode!=='simulation')throw error(400,'Only simulation mode is available in this build');if(body.auditRequired===false)throw error(400,'Audit logging is mandatory');if(body.criticalRisk!==undefined&&(!Number.isFinite(body.criticalRisk)||body.criticalRisk<1||body.criticalRisk>100))throw error(400,'Risk threshold must be 1–100');if(body.minConfidence!==undefined&&(!Number.isFinite(body.minConfidence)||body.minConfidence<0||body.minConfidence>1))throw error(400,'Confidence must be 0–1');const valid=DEFAULT_POLICY.allowedActions;if(body.allowedActions!==undefined&&(!Array.isArray(body.allowedActions)||body.allowedActions.some(x=>!valid.includes(x))))throw error(400,'Unknown allowed action');if(body.approvalRequired!==undefined&&(!Array.isArray(body.approvalRequired)||body.approvalRequired.some(x=>!valid.includes(x))))throw error(400,'Unknown approval rule');if(body.approvalRequired&&!DEFAULT_POLICY.approvalRequired.every(x=>body.approvalRequired.includes(x)))throw error(400,'High-impact actions must require approval');return {mode:'simulation',auditRequired:true,...Object.fromEntries(['criticalRisk','minConfidence','allowedActions','approvalRequired'].filter(k=>body[k]!==undefined).map(k=>[k,body[k]]))};}
function validateWeights(weights){if(!weights||typeof weights!=='object')throw error(400,'Weights required');for(const [key,value] of Object.entries(weights))if(!(key in DEFAULT_WEIGHTS)||!Number.isInteger(value)||value<0||value>100)throw error(400,`Invalid risk weight: ${key}`);return weights;}
const stepQuery=(req,id)=>{const raw=new URL(req.url,'http://localhost').searchParams.get('step');return raw===null?undefined:Number(raw);};
function ingestReal(event,retryJobId=null) {
  const id=event.metadata.scenario;
  if(event.metadata.simulation!==false||!realSources.includes(id))throw error(400,'Real-source provenance required');
  if(eventExists(tenantId(),event.id)){if(retryJobId)updateIngestionJob(tenantId(),retryJobId,'completed');return {eventId:event.id,scenarioId:id,duplicate:true};}
  const count=listIngestedEvents(tenantId(),id).length;
  if(count>=300)throw error(409,'Source workspace reached 300 events; collection paused. Export records and provision another workspace.');
  const jobId=retryJobId||enqueueIngestion(tenantId(),event.metadata.connector,{event});
  try{const a=processEvent(id,event,count+1);updateIngestionJob(tenantId(),jobId,'completed');return {eventId:event.id,scenarioId:id,duplicate:false,risk:a.risk,detected:a.detected};}catch(e){updateIngestionJob(tenantId(),jobId,'failed','Telemetry processing failed');throw e;}
}
let polling=false;
const externalRuns=new Set();
async function externalRun(scenarioId,step,maxQueries,actor){
  if(externalRuns.has(scenarioId))throw error(409,'An external investigation is already running for this source');
  if(tenantId()!=='default')throw error(403,'This Wazuh connector belongs to the default organization');
  if(!wazuhConfig())throw error(503,'Configure Wazuh before querying external evidence');
  const analysis=analysisFor(scenarioId,step);externalRuns.add(scenarioId);
  try{const result=await investigateExternalEvidence(analysis,{maxQueries});observePipeline('externalQueries',result.queriesUsed);observePipeline('externalFailures',result.trace.filter(t=>t.status==='failed').length);const saved=saveExternalInvestigation(tenantId(),scenarioId,{...result,step:analysis.events.length,modelVersion:analysis.modelVersion});audit('external-investigation',`${saved.id}: ${result.queriesUsed} read-only queries; ${result.stopReason}`,scenarioId,actor,analysis.events.length);return saved;}finally{externalRuns.delete(scenarioId);}
}
export async function pollWazuh() {
  if(tenantId()!=='default')throw error(403,'This Wazuh connector belongs to the default organization');
  if(polling)throw error(409,'Wazuh poll is already running');
  if(!wazuhConfig())throw error(503,'Configure the Wazuh endpoint and read-only credentials');
  polling=true;
  const prior=connectorState(tenantId(),'wazuh'),until=prior.pending?.until||new Date().toISOString(),from=prior.pending?.from||new Date(Date.parse(prior.checkpoint||until)-300000).toISOString();
  let offset=prior.pending?.offset||0,imported=0,duplicates=0;
  try{
    for(let page=0;page<3;page++){
      if(offset>=9900)throw error(409,'Wazuh window exceeds pagination limit; narrow the collection interval');
      const result=await queryWazuh({from,until,offset});
      for(const event of result.events){const saved=ingestReal(event);saved.duplicate?duplicates++:imported++;}
      offset+=result.events.length;
      const state={status:'connected',lastSuccess:new Date().toISOString(),failures:0,checkpoint:result.hasMore?prior.checkpoint||null:until,pending:result.hasMore?{from,until,offset}:null,imported,duplicates};
      saveConnectorState(tenantId(),'wazuh',state);
      if(!result.hasMore){audit('connector',`Wazuh poll imported ${imported}; duplicates ${duplicates}`,'wazuh','Connector worker');return state;}
    }
    return connectorState(tenantId(),'wazuh');
  }catch(e){const state=connectorState(tenantId(),'wazuh');saveConnectorState(tenantId(),'wazuh',{...state,status:'error',failures:(state.failures||0)+1,lastError:'Read-only collection failed; check configuration, capacity and upstream health',pending:state.pending||{from,until,offset}});throw e;
  }finally{polling=false;}
}
export function startConnectorWorker(){
  const interval=Number(process.env.SENTINEL_X_WAZUH_POLL_MS||0);
  if(!wazuhConfig()||!Number.isFinite(interval)||interval<10000)return ()=>{};
  let timer,stopped=false;
  const tick=async()=>{try{await pollWazuh();}catch{}if(!stopped){const failures=connectorState(tenantId(),'wazuh').failures||0;timer=setTimeout(tick,Math.min(300000,interval*2**Math.min(failures,5)));timer.unref();}};
  timer=setTimeout(tick,1000);timer.unref();return ()=>{stopped=true;clearTimeout(timer);};
}
export function startIngestionWorker(){
  const timer=setInterval(()=>{
    const rows=getDb().prepare("SELECT id,payload,attempts,updated_at FROM ingestion_jobs WHERE tenant_id='default' AND connector IN ('wazuh','authenticated-push') AND status IN ('queued','failed') AND attempts<3 ORDER BY created_at LIMIT 10").all();
    for(const row of rows){if(Date.now()-Date.parse(row.updated_at)<5000*2**row.attempts)continue;try{ingestReal(JSON.parse(row.payload).event,row.id);}catch{const latest=getIngestionJob('default',row.id);if(latest?.attempts===row.attempts)updateIngestionJob('default',row.id,'failed','Real telemetry retry failed');}}
  },5000);timer.unref();return ()=>clearInterval(timer);
}
export async function handleApi(req,res,pathname){const principal=principalFor(req);const tenant=pathname==='/api/v1/telemetry/events'?'default':principal?.tenantId||'default';return tenantScope.run(tenant,()=>handleScopedApi(req,res,versionedPath(pathname)));}
async function handleScopedApi(req,res,pathname){const method=req.method,parts=pathname.split('/').filter(Boolean);try{
  if(method==='POST'&&pathname.startsWith('/api/v1/auth/')){if(authMode()!=='local')throw error(409,'Local authentication is not enabled');const origin=req.headers.origin;if(origin&&origin!==(process.env.SENTINEL_X_PUBLIC_ORIGIN||(req.socket.encrypted?'https://':'http://')+req.headers.host))throw error(403,'Cross-origin authentication denied');const op=pathname.split('/').at(-1);if(op==='login')return json(res,200,await loginLocal(res,await parseBody(req),tenants));if(op==='refresh')return json(res,200,refreshLocal(req,res));if(op==='logout')return json(res,200,logoutLocal(req,res));throw error(404,'Unknown authentication operation');}
  if(method==='GET'&&parts[1]==='health')return json(res,200,{status:'ok',mode:'simulation',engine:'SENTINEL-X',version:'4.0.0',authentication:authMode()});
  if(method==='POST'&&pathname==='/api/v1/telemetry/events'){if(!telemetryAuthorized(req))throw error(401,'Telemetry source authentication required');const body=await parseBody(req),event=normalizeTelemetry(body.event||body);const result=ingestReal(event);return json(res,result.duplicate?200:201,result);}
  const principal=principalFor(req);
  if(!principal)throw error(401,'Authentication required');
  if(!tenants.has(principal.tenantId))throw error(403,'Tenant is not configured');
  if(!['GET','HEAD'].includes(method)){const origin=req.headers.origin;if(origin&&origin!==(process.env.SENTINEL_X_PUBLIC_ORIGIN||(req.socket.encrypted?'https://':'http://')+req.headers.host))throw error(403,'Cross-origin mutation denied');if(req.headers['x-sentinel-demo-token']!==DEMO_TOKEN)throw error(401,'Session token required');const required=['policy','weights','ingest','ingestion-jobs','model-ops','rollbacks','connectors'].includes(parts[1])?'admin':'analyst';if(!hasRole(principal,required))throw error(403,'Insufficient role');}
  if(method==='GET'&&parts[1]==='session')return json(res,200,{token:DEMO_TOKEN,mode:'simulation',authentication:authMode(),actor:principal.actor,role:principal.role,tenantId:principal.tenantId});
  if(method==='GET'&&parts[1]==='scenarios'){const all=[...scenarios,...realSources.filter(id=>listIngestedEvents(tenantId(),id).length).map(scenarioFor)];if(listIngestedEvents(tenantId(),'live').length)all.push(scenarioFor('live'));return json(res,200,all.map(s=>({id:s.id,name:s.name,incidentId:s.incidentId,eventCount:s.events.length,simulation:!realSources.includes(s.id)})));}
  if(method==='GET'&&parts[1]==='entities')return json(res,200,listEntities(tenantId()));
  if(method==='GET'&&parts[1]==='events'&&!parts[2]){
    const url=new URL(req.url,'http://localhost'),{limit,offset}=pageParameters(url),scenario=url.searchParams.get('scenarioId'),type=url.searchParams.get('type');
    const clauses=['tenant_id=?'],params=[tenantId()];if(scenario){scenarioFor(scenario);clauses.push('scenario_id=?');params.push(scenario);}if(type){clauses.push('type=?');params.push(type);}
    const where=clauses.join(' AND '),db=getDb(),total=db.prepare('SELECT COUNT(*) AS count FROM events WHERE '+where).get(...params).count;
    const items=db.prepare('SELECT payload FROM events WHERE '+where+' ORDER BY timestamp ASC,id ASC LIMIT ? OFFSET ?').all(...params,limit,offset).map(row=>JSON.parse(row.payload));return json(res,200,{items,total,limit,offset});
  }
  if(method==='GET'&&['risk','attack-graphs'].includes(parts[1])&&parts[2]){const a=analysisFor(parts[2],stepQuery(req,parts[2]));return json(res,200,parts[1]==='risk'?{score:a.risk,rawRisk:a.rawRisk,formula:'round(100*(1-exp(-rawRisk/75)))',factors:a.riskFactors,weights:getWeights(tenantId()),confidence:a.confidence,modelVersion:a.modelVersion,severity:a.severity}:{nodes:a.graphNodes,edges:a.graphEdges,correlations:a.correlations});}
  if(method==='GET'&&parts[1]==='investigation-agent'&&parts[2]){const url=new URL(req.url,'http://localhost'),maxSteps=url.searchParams.has('maxSteps')?Number(url.searchParams.get('maxSteps')):5;if(!Number.isInteger(maxSteps)||maxSteps<1||maxSteps>5)throw error(400,'Investigation budget must be 1–5 steps');const a=analysisFor(parts[2],stepQuery(req,parts[2]));return json(res,200,{scenarioId:parts[2],step:a.events.length,...runInvestigation(a,{maxSteps})});}
  if(method==='GET'&&parts[1]==='topology')return json(res,200,listTopology(tenantId()));
  if(method==='GET'&&parts[1]==='model-ops'&&parts[2]==='deployed')return json(res,200,deployedArtifact(tenantId()));
  if(method==='GET'&&parts[1]==='model-ops')return json(res,200,modelOperations(tenantId()));
  if(method==='POST'&&parts[1]==='model-ops'&&parts[2]==='train'){const body=await parseBody(req);if(modelOperations(tenantId()).versions.some(v=>v.version===body.version))throw error(409,'Model version already exists');let trained;try{trained=await trainInWorker(body);}catch(e){throw error(e.status||400,e.message);}const result=saveCandidate(tenantId(),body,trained);audit('model-training',`Trained ${body.version}; held-out evaluation eligible: ${trained.metrics.eligible}`,null,principal.actor);return json(res,201,result);}
  if(method==='GET'&&parts[1]==='connectors')return json(res,200,{mode:'read-only-vendor-integration',connectors:['authentication','network','endpoint','server','cloud','application','firewall','identity'].map(type=>({type,status:'configuration-required',schema:'unified-security-event-v1'})),wazuh:{configured:tenantId()==='default'&&Boolean(wazuhConfig()),...connectorState(tenantId(),'wazuh'),readOnly:true},queue:ingestionHealth(tenantId())});
  if(method==='POST'&&parts[1]==='connectors'&&parts[2]==='wazuh'&&parts[3]==='poll')return json(res,200,await pollWazuh());
  if(method==='POST'&&parts[1]==='model-ops'&&parts[2]==='register'){const body=await parseBody(req);if(!/^[a-zA-Z0-9._-]{3,80}$/.test(String(body.version||'')))throw error(400,'Valid model version required');return json(res,201,registerModelVersion(tenantId(),{version:body.version,algorithm:String(body.algorithm||'').slice(0,200),metrics:body.metrics,parentVersion:body.parentVersion}));}
  if(method==='POST'&&parts[1]==='model-ops'&&parts[2]==='promote'){const body=await parseBody(req);try{const result=promoteTrainedModel(tenantId(),String(body.version||''));audit('model-deployment','Deployed inference model '+result.activeVersion,null,principal.actor);return json(res,200,result);}catch(e){throw error(400,e.message);}}
  if(method==='POST'&&parts[1]==='model-ops'&&parts[2]==='rollback'){try{const result=rollbackTrainedModel(tenantId());audit('model-rollback','Restored inference model '+result.activeVersion,null,principal.actor);return json(res,200,result);}catch(e){throw error(409,e.message);}}
  if(method==='POST'&&parts[1]==='model-ops'&&parts[2]==='drift'){const body=await parseBody(req),ops=modelOperations(tenantId()),score=Number(body.score);if(!Number.isFinite(score)||score<0||score>1)throw error(400,'Drift score must be 0–1');return json(res,201,recordModelDrift(tenantId(),{modelVersion:ops.activeVersion,sampleCount:Math.max(0,Number(body.sampleCount)||0),score,details:body.details}));}
  if(method==='GET'&&parts[1]==='events'&&parts[2])return json(res,200,listIngestedEvents(tenantId(),parts[2]));
  if(method==='GET'&&parts[1]==='snapshots'&&parts[2])return json(res,200,listSnapshots(tenantId(),parts[2],new URL(req.url,'http://localhost').searchParams.get('all')==='1'));
  if(method==='GET'&&parts[1]==='analyze'&&parts[2]){const step=stepQuery(req,parts[2]),a=analysisFor(parts[2],step),status=getIncidentStatus(tenantId(),parts[2]);return json(res,200,{scenarioId:parts[2],step:step??a.events.length,analysis:a,status:status?.status||'NEW',note:status?.note||''});}
  if(method==='GET'&&parts[1]==='dashboard'){const all=[...scenarios,...realSources.filter(id=>listIngestedEvents(tenantId(),id).length).map(scenarioFor)];if(listIngestedEvents(tenantId(),'live').length)all.push(scenarioFor('live'));const analyses=all.map(s=>analysisFor(s.id));const pending=analyses.filter((a,i)=>a.policy.approval&&!listActions(tenantId(),all[i].id).some(x=>x.action===a.policy.action&&x.status==='approved')).length;return json(res,200,{analyses:all.map((s,i)=>({scenarioId:s.id,incidentId:s.incidentId,name:s.name,...analyses[i]})),briefing:securityBriefing(analyses,pending)});}
  if(method==='POST'&&parts[1]==='ingest'){const body=await parseBody(req),connector=String(req.headers['x-sentinel-connector']||'demo-api').slice(0,80),jobId=enqueueIngestion(tenantId(),connector,body);try{const event=normalize(body.event);if(!event.metadata.simulation)throw error(400,'Live production ingestion is unavailable in simulation mode');event.metadata.scenario='live';const current=listIngestedEvents(tenantId(),'live');if(current.some(e=>e.id===event.id))throw error(409,'Event ID already ingested');const step=current.length+1,a=processEvent('live',event,step),job=updateIngestionJob(tenantId(),jobId,'completed');return json(res,201,{job,eventId:event.id,scenarioId:'live',step,detected:a.detected,risk:a.risk});}catch(e){updateIngestionJob(tenantId(),jobId,'failed',e.message);throw e;}}
  if(method==='POST'&&parts[1]==='ingestion-jobs'&&parts[3]==='retry'){const job=getIngestionJob(tenantId(),parts[2]);if(!job)throw error(404,'Ingestion job not found');if(job.status==='completed')throw error(409,'Job already completed');if(['wazuh','authenticated-push'].includes(job.connector)&&job.payload.event?.metadata?.simulation===false){if(job.status==='dead-letter')throw error(409,'Dead-letter job requires source correction before resubmission');return json(res,200,{...ingestReal(job.payload.event,job.id),job:getIngestionJob(tenantId(),job.id)});}try{const event=normalize(job.payload.event);if(!event.metadata.simulation)throw error(400,'Live production ingestion is unavailable in simulation mode');event.metadata.scenario='live';const current=listIngestedEvents(tenantId(),'live');if(current.some(e=>e.id===event.id))throw error(409,'Event ID already ingested');const a=processEvent('live',event,current.length+1);return json(res,200,{job:updateIngestionJob(tenantId(),job.id,'completed'),detected:a.detected,risk:a.risk});}catch(e){const updated=updateIngestionJob(tenantId(),job.id,'failed',e.message);return json(res,updated.status==='dead-letter'?422:409,{job:updated,error:e.message});}}
  if(method==='POST'&&parts[1]==='rollbacks'){const body=await parseBody(req);if(!String(body.reason||'').trim())throw error(400,'Rollback reason required');try{const result=rollbackSimulatedControl(tenantId(),String(body.scenarioId||''),String(body.action||''),String(body.target||''),principal.actor,String(body.reason).slice(0,1000));audit('rollback',`${result.action} on ${result.target}: ${result.reason}`,body.scenarioId,principal.actor);return json(res,201,result);}catch(e){throw error(404,e.message);}}
  if(method==='POST'&&parts[1]==='simulate'&&parts[2]&&parts[3]==='reset'){const s=scenarioFor(parts[2]);if(parts[2]==='live'||realSources.includes(parts[2]))throw error(400,'Use live ingestion for live scenario');clearScenarioEvents(tenantId(),parts[2]);upsertIncidentStatus(tenantId(),s.id,s.incidentId,'NEW','');audit('simulation',`Reset event replay for ${parts[2]}`,parts[2]);return json(res,200,{ok:true,step:0,runId:currentRun(tenantId(),s.id)});}
  if(method==='POST'&&parts[1]==='simulate'&&parts[2]&&parts[3]==='step'){const s=scenarioFor(parts[2]),body=await parseBody(req),step=Number(body.step);if(s.id==='live'||realSources.includes(s.id)||!Number.isInteger(step)||step<1||step>s.events.length)throw error(400,'Invalid replay step');const ingested=listIngestedEvents(tenantId(),s.id);if(step!==ingested.length+1)throw error(409,'Replay steps must be sequential');const a=processEvent(s.id,normalize(s.events[step-1]),step);return json(res,200,{step,analysis:a});}
  if(method==='POST'&&parts[1]==='investigate'){const body=await parseBody(req),s=scenarioFor(body.scenarioId),a=analysisFor(s.id,body.step);observePipeline('aiRequests');const answer=await investigateWithGrounding(String(body.question||''),a,s,{actions:listActions(tenantId(),s.id)});if(answer.provider==='deterministic-fallback')observePipeline('aiFallbacks');return json(res,200,answer);}
  if(method==='POST'&&parts[1]==='investigations'&&parts[2]==='external'){const body=await parseBody(req);return json(res,201,await externalRun(body.scenarioId,body.step,body.maxQueries??3,principal.actor));}
  if(method==='GET'&&parts[1]==='investigations'&&parts[2]){scenarioFor(parts[2]);return json(res,200,listExternalInvestigations(tenantId(),parts[2]));}
  if(method==='GET'&&parts[1]==='ai-status')return json(res,200,{provider:llmProvider(),grounding:'event evidence retrieval',citationValidation:true,promptInjectionProtection:true,inputRedaction:true});
  if(method==='GET'&&parts[1]==='policy')return json(res,200,getPolicy(tenantId()));
  if(method==='PUT'&&parts[1]==='policy'){const patch=validatePolicy(await parseBody(req)),updated=updatePolicy(tenantId(),patch);setPolicy(updated);audit('policy',`Simulation policy updated: risk ${updated.criticalRisk}, confidence ${updated.minConfidence}`,null);return json(res,200,updated);}
  if(method==='GET'&&parts[1]==='weights')return json(res,200,getWeights(tenantId()));
  if(method==='PUT'&&parts[1]==='weights'){const body=await parseBody(req),updated=updateWeights(tenantId(),validateWeights(body.weights||body));setWeights(updated);audit('config','Risk weights updated',null);return json(res,200,updated);}
  if(method==='GET'&&parts[1]==='audit')return json(res,200,listAudit(tenantId(),parts[2],new URL(req.url,'http://localhost').searchParams.get('all')==='1'));
  if(method==='GET'&&parts[1]==='feedback')return json(res,200,listFeedback(tenantId(),parts[2]));
  if(method==='POST'&&parts[1]==='feedback'){const body=await parseBody(req),scenario=scenarioFor(body.scenarioId);if(listIngestedEvents(tenantId(),scenario.id).length<scenario.events.length)throw error(409,'Complete the replay before classifying the incident');if(!['confirmed_attack','false_positive','needs_investigation'].includes(body.classification)||!String(body.reason||'').trim())throw error(400,'Classification and reason required');const entry={id:`FB-${randomUUID()}`,tenantId:tenantId(),scenarioId:body.scenarioId,classification:body.classification,reason:String(body.reason).slice(0,1000),analyst:principal.actor,timestamp:new Date().toISOString(),runId:currentRun(tenantId(),body.scenarioId)};insertFeedback(entry);audit('feedback',`${entry.classification}: ${entry.reason}`,entry.scenarioId,entry.analyst);broadcast('feedback',entry);return json(res,201,entry);}
  if(method==='POST'&&parts[1]==='actions'){const body=await parseBody(req),s=scenarioFor(body.scenarioId),step=body.step===undefined?s.events.length:Number(body.step),a=analysisFor(s.id,step);if(!['approved','rejected'].includes(body.status))throw error(400,'Decision must be approved or rejected');if(step>listIngestedEvents(tenantId(),s.id).length)throw error(409,'Replay the evidence before recording a response decision');if(!a.policy.action||body.action!==a.policy.action||!getPolicy(tenantId()).allowedActions.includes(body.action))throw error(403,'Action is not authorized by current evidence and policy');if(body.policyId&&body.policyId!==a.policy.policyId)throw error(403,'Policy mismatch');if(listActions(tenantId(),s.id).some(x=>x.action===body.action&&x.status==='approved'))throw error(409,'Action was already approved in this replay');const actor=principal.actor,reason=String(body.reason||'').trim();if(!reason)throw error(400,'Reason required');const entry=recordAction(s.id,a.policy.action,body.status,reason,actor,step,a);return json(res,201,entry);}
  if(method==='GET'&&parts[1]==='actions'&&parts[2]){scenarioFor(parts[2]);return json(res,200,listActions(tenantId(),parts[2],new URL(req.url,'http://localhost').searchParams.get('all')==='1'));}
  if(method==='GET'&&parts[1]==='incidents'&&parts[2]){const s=scenarioFor(parts[2]),row=getIncidentStatus(tenantId(),s.id);return json(res,200,{incidentId:s.incidentId,status:row?.status||'NEW',note:row?.note||'',runId:currentRun(tenantId(),s.id),actions:listActions(tenantId(),s.id),controls:listSimulatedControls(tenantId(),s.id),feedback:listFeedback(tenantId(),s.id),audit:listAudit(tenantId(),s.id)});}
  if(method==='PUT'&&parts[1]==='incidents'&&parts[2]&&parts[3]==='status'){const s=scenarioFor(parts[2]),body=await parseBody(req),states=['NEW','INVESTIGATING','CONTAINMENT','RESOLVED','CLOSED'],current=getIncidentStatus(tenantId(),s.id)?.status||'NEW',next=body.status;if(listIngestedEvents(tenantId(),s.id).length<s.events.length)throw error(409,'Complete the replay before changing incident status');if(!states.includes(next)||states.indexOf(next)>states.indexOf(current)+1||states.indexOf(next)<states.indexOf(current))throw error(400,'Invalid lifecycle transition');const row=upsertIncidentStatus(tenantId(),s.id,s.incidentId,next,String(body.note||'').slice(0,5000));audit('lifecycle',`${s.incidentId}: ${current} → ${next}`,s.id,principal.actor);return json(res,200,row);}
  if(method==='GET'&&parts[1]==='report'&&parts[2]){const s=scenarioFor(parts[2]),step=stepQuery(req,s.id),a=analysisFor(s.id,step),full=a.events.length===s.events.length,allActions=listActions(tenantId(),s.id),state={actions:full?allActions:allActions.filter(x=>x.step!==null&&x.step<=a.events.length),audit:full?listAudit(tenantId(),s.id):[],status:full?(getIncidentStatus(tenantId(),s.id)?.status||'NEW'):'NEW',note:full?(getIncidentStatus(tenantId(),s.id)?.note||''):'',feedback:full?listFeedback(tenantId(),s.id):[],externalInvestigations:full?listExternalInvestigations(tenantId(),s.id):[]},data=report(s,a,state),format=parts[3]||'json';if(format==='csv'){res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${s.incidentId}.csv"`});return res.end(reportCsv(data));}if(format==='html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(reportPdfHtml(s,a,state));}if(format==='pdf'){const bytes=renderReportPdf(data);res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${s.incidentId}.pdf"`,'Content-Length':bytes.length});return res.end(bytes);}if(format!=='json')throw error(404,'Unknown report format');return json(res,200,data);}
  if(method==='GET'&&parts[1]==='compare'){const url=new URL(req.url,'http://localhost'),idA=url.searchParams.get('a'),idB=url.searchParams.get('b'),sA=scenarioFor(idA),sB=scenarioFor(idB),stepA=url.searchParams.has('step')?Number(url.searchParams.get('step')):undefined,a=analysisFor(idA,stepA),cutoff=a.events.at(-1)?.timestamp||'',observedB=listIngestedEvents(tenantId(),idB).length,visibleB={...sB,events:sB.events.slice(0,observedB).filter(e=>e.timestamp<=cutoff)},b=analyze(visibleB,visibleB.events.length,listFeedback(tenantId(),idB).filter(f=>f.runId<currentRun(tenantId(),idB)),settings());const actions=(id,analysis)=>listActions(tenantId(),id).filter(x=>x.step<=analysis.events.length&&(x.evidenceIds||[]).every(e=>analysis.evidence.some(v=>v.id===e)));return json(res,200,compareIncidents(a,b,sA,sB,{actions:actions(idA,a)},{actions:actions(idB,b)}));}
  if(method==='GET'&&parts[1]==='stream'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache',Connection:'keep-alive'});res.write('event: connected\ndata: {}\n\n');sseClients.set(res,{tenant:tenantId(),req});const expiry=setTimeout(()=>res.end(),900000);expiry.unref();req.on('close',()=>{clearTimeout(expiry);sseClients.delete(res);});return;}
  return json(res,404,{error:'Not found'});
}catch(e){if(!e.status)console.error('SENTINEL-X API error:',e);return json(res,e.status||500,{error:e.status?e.message:'Server error'});}}
