import {operationActions,handleOperation} from './operations.js';
import {answer,report,reportCsv,DEFAULT_POLICY} from '../engine.js';
import {api} from '../api.js';
import {download,downloadBlob} from '../lib/utils.js';
import {store} from './state.js';
import {getAnalysis,getScenario} from './context.js';
const notify=(message,error=false)=>{store.state.uiError=error?message:'';store.state.uiNotice=error?'':message;};
const actionTarget=(action,a)=>action.includes('endpoint')?a.affected.devices[0]:action.includes('source')?(a.events.at(-1)?.ip||a.events.at(-1)?.destination||a.events.at(-1)?.source):action.includes('session')||action.includes('account')?a.affected.accounts[0]:'Security operations queue';
export function audit(type,detail){store.audit.unshift({id:`LOCAL-${Date.now()}`,type,detail,actor:'Demo analyst',timestamp:new Date().toISOString(),scenarioId:store.state.scenarioId,simulation:true});}
async function refreshAudit(){if(store.state.apiOnline)store.audit=await api.audit();}
export function setStep(n,render){const s=getScenario(),limit=store.state.apiOnline?(store.processedSteps[s.id]||0):s.events.length;store.state.step=Math.max(0,Math.min(limit,n));store.state.answer='';store.state.answerEvidence=[];render();}
export function stopReplay(render){clearTimeout(store.timer);store.state.playing=false;render();}
export async function startReplay(render){clearTimeout(store.timer);const s=getScenario();if(['live','telemetry','wazuh'].includes(s.id)){notify('Live events arrive through the ingestion API. Use the time slider to inspect them.',true);return render();}try{if(store.state.apiOnline){const reset=await api.simulateReset(s.id);store.runIds[s.id]=reset.runId;store.actions=store.actions.filter(x=>x.scenarioId!==s.id);await refreshAudit();store.state.incidentStatus='NEW';store.state.note='';}store.processedSteps[s.id]=0;notify('Replay started. Events are processed in order.');store.state.step=0;store.state.playing=true;render();const next=async()=>{if(!store.state.playing)return;if(store.state.step>=s.events.length){store.state.playing=false;notify('Replay complete. Review the evidence, policy, report and feedback.');return render();}const step=store.state.step+1;try{if(store.state.apiOnline){await api.simulateStep(s.id,step);store.actions=[...store.actions.filter(x=>x.scenarioId!==s.id),...await api.actions(s.id)];await refreshAudit();}store.processedSteps[s.id]=step;store.state.step=step;render();store.timer=setTimeout(next,850);}catch(err){store.state.playing=false;notify(err.message,true);render();}};store.timer=setTimeout(next,300);}catch(err){notify(err.message,true);render();}}
export async function loadScenarioState(id,render){stopReplay(()=>{});store.state.scenarioId=id;store.state.step=store.processedSteps[id]||0;store.state.answer='';store.state.comparison=null;store.state.incidentStatus='NEW';store.state.note='';if(store.state.apiOnline){try{const row=await api.incident(id);store.actions=[...store.actions.filter(x=>x.scenarioId!==id),...row.actions];store.state.incidentStatus=row.status;store.state.note=row.note;store.runIds[id]=row.runId;store.feedback=await api.feedbackList();await refreshAudit();notify('');}catch(err){notify(err.message,true);}}render();}
export async function askQuestion(root,render){store.state.question=root.querySelector('#question')?.value.trim()||store.state.question;if(!store.state.question){notify('Enter an investigation question.',true);return render();}try{if(store.state.apiOnline){const scenarioId=store.state.scenarioId,step=store.state.step,runId=store.runIds[scenarioId];const result=await api.investigate(scenarioId,store.state.question,step);if(store.state.scenarioId!==scenarioId||store.state.step!==step||store.runIds[scenarioId]!==runId)return;store.state.answer=result.answer;store.state.answerEvidence=result.evidence||[];}else{store.state.answer=answer(store.state.question,getAnalysis(),getScenario(),{actions:store.actions});store.state.answerEvidence=getAnalysis().evidence.map(e=>e.id);}notify('');}catch(err){notify(err.message,true);}render();}
export async function submitFeedback(root,classification,render){const s=getScenario();if(store.state.step<s.events.length||(store.state.apiOnline&&(store.processedSteps[s.id]||0)<s.events.length)){notify('Complete the replay before classifying the incident.',true);return render();}const reason=root.querySelector('#feedback-reason')?.value.trim();if(!reason){notify('Enter a reason for analyst feedback.',true);return render();}try{const entry={scenarioId:store.state.scenarioId,classification,reason,analyst:'Demo analyst'};if(store.state.apiOnline){const saved=await api.feedback(entry);if(!store.feedback.some(x=>x.id===saved.id))store.feedback.unshift(saved);await refreshAudit();}else{store.feedback.unshift({...entry,runId:store.runIds[s.id]||0,timestamp:new Date().toISOString()});audit('feedback',`${classification}: ${reason}`);}notify('Feedback saved; this scenario’s detection threshold has been updated.');}catch(err){notify(err.message,true);}render();}
export async function handleAction(action,root,render){if(action==='toggle-theme'){store.state.theme=store.state.theme==='dark'?'light':'dark';localStorage.setItem('sentinel-x-theme',store.state.theme);return render();}if(action==='logout'){try{if(store.state.session?.authentication==='local')await api.logout();}catch{}sessionStorage.removeItem('sentinel-x-signed-in');location.reload();return;}if(operationActions.includes(action))return handleOperation(action,root,render);const a=getAnalysis(),s=getScenario();if(action==='replay-history'){clearTimeout(store.timer);const limit=s.events.length;store.state.step=0;store.state.answer='';store.state.playing=true;render();const tick=()=>{if(!store.state.playing)return;store.state.step++;if(store.state.step>=limit)store.state.playing=false;render();if(store.state.playing)store.timer=setTimeout(tick,850);};if(limit)store.timer=setTimeout(tick,300);else store.state.playing=false;return;}if(action==='start')return startReplay(render);if(action==='stop')return stopReplay(render);if(action==='ask')return askQuestion(root,render);try{
  if(action==='save-policy'){const patch={criticalRisk:Number(root.querySelector('#pol-risk').value),minConfidence:Number(root.querySelector('#pol-conf').value),allowedActions:[...root.querySelectorAll('[data-allowed-action]:checked')].map(el=>el.dataset.allowedAction),approvalRequired:[...new Set([...DEFAULT_POLICY.approvalRequired,...[...root.querySelectorAll('[data-approval-action]:checked')].map(el=>el.dataset.approvalAction)])]};if(store.state.apiOnline){store.state.policy=await api.policy.update(patch);await refreshAudit();}else{store.state.policy={...store.state.policy,...patch,mode:'simulation'};audit('policy','Simulation policy updated');}notify('Simulation policy saved.');}
  else if(action==='save-weights'){const weights={};root.querySelectorAll('[data-weight]').forEach(el=>{weights[el.dataset.weight]=Number(el.value);});if(store.state.apiOnline){store.state.weights=await api.weights.update(weights);await refreshAudit();}else{store.state.weights={...store.state.weights,...weights};audit('config','Risk weights updated');}notify('Risk weights saved.');}
  else if(action==='status'||action==='note'){if(store.state.step<s.events.length||(store.state.apiOnline&&(store.processedSteps[s.id]||0)<s.events.length))throw Error('Complete the replay before changing incident status.');const status=action==='status'?(root.querySelector('#status')?.value||store.state.incidentStatus):store.state.incidentStatus;const note=root.querySelector('#note')?.value||store.state.note;if(store.state.apiOnline){await api.status(s.id,status,note);await refreshAudit();}else audit('lifecycle',`${s.incidentId}: ${status}`);store.state.incidentStatus=status;store.state.note=note;notify(action==='note'?'Investigation note saved.':'Incident status updated.');}
  else if(['export','export-csv','export-pdf'].includes(action)){const reportState={actions:store.actions.filter(x=>x.scenarioId===s.id&&(x.step??Infinity)<=store.state.step),audit:store.state.step===s.events.length?store.audit.filter(x=>x.scenarioId===s.id):[],status:store.state.step===s.events.length?store.state.incidentStatus:'NEW',note:store.state.step===s.events.length?store.state.note:''};if(action==='export-pdf'){if(!store.state.apiOnline)throw Error('PDF export requires the local API server.');downloadBlob(`${s.incidentId}.pdf`,await api.reportPdf(s.id,store.state.step));}else if(store.state.apiOnline){const format=action==='export'?'json':'csv';const data=await api.report(s.id,format,store.state.step);download(`${s.incidentId}.${format}`,format==='json'?JSON.stringify(data,null,2):data,format==='json'?'application/json':'text/csv');}else{const data=report(s,a,reportState);if(action==='export')download(`${s.incidentId}.json`,JSON.stringify(data,null,2),'application/json');else download(`${s.incidentId}.csv`,reportCsv(data),'text/csv');}notify('Historical incident report exported.');}
  else if(action==='approve'||action==='reject'){if(!a.policy.action)throw Error('No policy action is available at this historical point.');if(store.state.apiOnline&&(store.processedSteps[s.id]||0)<store.state.step)throw Error('Replay the evidence before recording a response decision.');const entry={scenarioId:s.id,action:a.policy.action,status:action==='approve'?'approved':'rejected',reason:root.querySelector('#response-reason')?.value.trim()||`Demo analyst ${action==='approve'?'approved':'rejected'} the proposed action`,policyId:a.policy.policyId,actor:'Demo analyst',step:store.state.step};if(store.state.apiOnline){const saved=await api.action(entry);if(!store.actions.some(x=>x.id===saved.id))store.actions.unshift(saved);await refreshAudit();}else{const saved={...entry,result:entry.status==='approved'?'Simulated state recorded; no external change':'No action taken',timestamp:new Date().toISOString(),target:actionTarget(entry.action,a)||'Unattributed target',risk:a.risk,confidence:a.confidence,evidenceIds:a.evidence.map(e=>e.id)};store.actions.unshift(saved);audit('approval',`${saved.status}: ${saved.action} on ${saved.target}; risk ${saved.risk}/100, confidence ${Math.round(saved.confidence*100)}%, evidence ${saved.evidenceIds.join(', ')}, policy ${saved.policyId}. ${saved.reason}`);}notify(`${entry.action}: ${entry.status}. This was a simulated action.`);}
}catch(err){notify(err.message,true);}render();}
