const base = '2026-09-19T';
function event(id, time, type, action, extra={}) { return {id, timestamp:base+time+':00Z',type,action,sourceType:extra.sourceType||'authentication',source:extra.source||'Demo telemetry',destination:extra.destination||null,user:extra.user||null,account:extra.account||null,device:extra.device||null,ip:extra.ip||null,asset:extra.asset||null,severity:extra.severity||'medium',raw:{simulated:true,...extra.raw},normalized:{location:extra.location||null,bytes:extra.bytes||0,failures:extra.failures||0},metadata:{simulation:true,scenario:extra.scenario||'account',...extra.metadata}}; }
export const scenarios = [
 {id:'account',name:'Account compromise',incidentId:'SX-2401',summary:'Credential attack followed by sensitive access and possible exfiltration',entities:{user:'Maya Chen',account:'mchen',device:'Endpoint-07',ip:'198.51.100.42',asset:'Finance Vault',server:'File-Server-02',application:'Finance Portal'},events:[
  event('AC-01','02:13','auth_failure','27 failed login attempts',{user:'Maya Chen',account:'mchen',ip:'198.51.100.42',failures:27,severity:'high',location:'Unknown region'}),
  event('AC-02','02:14','auth_success','Successful login from unknown device',{user:'Maya Chen',account:'mchen',device:'Endpoint-07',ip:'198.51.100.42',location:'Unknown region',severity:'high'}),
  event('AC-03','02:15','privilege_escalation','Privilege elevated to finance administrator',{user:'Maya Chen',account:'mchen',device:'Endpoint-07',asset:'Finance Portal',sourceType:'identity',severity:'critical'}),
  event('AC-04','02:16','sensitive_access','Sensitive files accessed',{user:'Maya Chen',account:'mchen',device:'Endpoint-07',asset:'Finance Vault',sourceType:'application',severity:'high'}),
  event('AC-05','02:18','internal_access','Internal server accessed',{user:'Maya Chen',account:'mchen',device:'Endpoint-07',destination:'File-Server-02',asset:'File-Server-02',sourceType:'server',severity:'high'}),
  event('AC-06','02:19','outbound_transfer','Abnormal outbound transfer: 2.4 GB',{user:'Maya Chen',account:'mchen',device:'Endpoint-07',source:'File-Server-02',destination:'203.0.113.19',ip:'203.0.113.19',asset:'Finance Vault',sourceType:'network',bytes:2400000000,severity:'critical'})]},
 {id:'lateral',name:'Lateral movement',incidentId:'SX-2402',summary:'Endpoint activity traverses two internal systems',entities:{user:'Noah Patel',account:'npatel',device:'Endpoint-12',ip:'10.20.4.12',asset:'Customer Records',server:'App-Server-03',application:'Records Service'},events:[
  event('LM-01','03:41','endpoint_alert','Unusual process on endpoint',{scenario:'lateral',sourceType:'endpoint',user:'Noah Patel',account:'npatel',device:'Endpoint-12',severity:'medium'}),
  event('LM-02','03:43','internal_access','Internal authentication to App-Server-03',{scenario:'lateral',user:'Noah Patel',account:'npatel',device:'Endpoint-12',destination:'App-Server-03',asset:'App-Server-03',severity:'high'}),
  event('LM-03','03:46','internal_access','Second server reached: DB-Server-01',{scenario:'lateral',sourceType:'server',user:'Noah Patel',account:'npatel',device:'Endpoint-12',source:'App-Server-03',destination:'DB-Server-01',asset:'DB-Server-01',severity:'high'}),
  event('LM-04','03:48','sensitive_access','Customer records queried',{scenario:'lateral',sourceType:'application',user:'Noah Patel',account:'npatel',device:'Endpoint-12',asset:'Customer Records',severity:'high'})]},
 {id:'transfer',name:'Suspicious transfer',incidentId:'SX-2403',summary:'Sensitive access and unusual outbound volume',entities:{user:'Ava Rodriguez',account:'arodriguez',device:'Laptop-05',ip:'10.20.8.5',asset:'Design Archive',server:'Archive-01',application:'Archive Service'},events:[
  event('DT-01','04:12','normal_activity','Routine archive session',{scenario:'transfer',sourceType:'application',user:'Ava Rodriguez',account:'arodriguez',device:'Laptop-05',asset:'Design Archive',severity:'low'}),
  event('DT-02','04:18','sensitive_access','Unusual bulk archive access',{scenario:'transfer',sourceType:'application',user:'Ava Rodriguez',account:'arodriguez',device:'Laptop-05',asset:'Design Archive',severity:'high'}),
  event('DT-03','04:22','outbound_transfer','Abnormal outbound transfer: 1.1 GB',{scenario:'transfer',sourceType:'firewall',user:'Ava Rodriguez',account:'arodriguez',device:'Laptop-05',source:'Archive-01',destination:'203.0.113.88',asset:'Design Archive',bytes:1100000000,severity:'high'})]}
];
export const baseline={loginHourMedian:10,loginHourMad:2,failedLoginMedian:1,failedLoginMad:1,outboundBytesMedian:12000000,outboundBytesMad:8000000,knownDevices:['Laptop-05'],knownIPs:['10.20.8.5'],knownLocations:['Corporate office'],maintenanceWindows:[],corporateVpnRanges:['10.20.0.0/16'],assetCriticality:{'Finance Vault':5,'Customer Records':5,'Design Archive':4,'Finance Portal':4},users:{'Maya Chen':{loginHourMedian:10,knownDevices:['Workstation-03'],knownIPs:['10.20.4.21'],knownLocations:['Corporate office'],failedLoginMedian:1},'Noah Patel':{loginHourMedian:11,knownDevices:['Endpoint-12'],knownIPs:['10.20.4.12'],knownLocations:['Corporate office'],failedLoginMedian:1},'Ava Rodriguez':{loginHourMedian:9,knownDevices:['Laptop-05'],knownIPs:['10.20.8.5'],knownLocations:['Corporate office'],failedLoginMedian:1}}};
